### ISSUE TITLE
jsonpickle returns a <dict> object without error or warning when a class is not instantiable because a module it uses is not found.

### ISSUE THREAD

**Issue by Penumbra69** [jsonpickle/jsonpickle#313] opened 2020-06-22 23:02 UTC
Greetings! 

I use jsonpickle to persist a class to be transported for a Spark job.  In that environment, I have tried to keep in parity with modules used vs modules needing to be transported and added to the PYTHONPATH vs modules available within the spark environment on the executors/workers.

It works! Nice! But ...

As I was testing this flow - I found that one of my test cases was failing with a strange error:

The pickled class' JSON looks like this:
```
{'py/object': 'smoke.test.PersistSampleToLake', '_extra_kwargs': {'rows': '10'}}
```

And when attempting to read the jsonpickle -- it didn't complain or error out:
```
2020-06-22,17:31:08.195 INFO {spark_driver} [<module>] Spark-Driver read pickled class <class 'dict'>
```

However it wasn't the class I thought it was:
```
2020-06-22,17:31:08.195 INFO {spark_driver} [<module>] Executing dict.execute_in_spark()
Traceback (most recent call last):
  File "spark_driver.py", line 32, in <module>
    runner.execute_in_spark()
AttributeError: 'dict' object has no attribute 'execute_in_spark'
``` 
Note that the class it loaded was returned as a ```<dict>``` - not my class "smoke.test.PersistSampleToLake" which DOES have an "execute_in_spark()" function.

In triaging this - I found that there was a module "sklearn" which was being utilized by the author in this case, that wasn't present on the executor / worker machines.  Seems fair that it can't decode a class that is referencing something the pickler can't see.  Quite fair.

What I expected:
XXXXXError - attempting to decode a class using a module we can't find "sklearn"

What I received:
No Warning
No Error
a <dict> object containing my pickle.

Can we enhance the error reporting portion of this tool to be a little more vocal about actual ERRORS which will stop the parsing and just hand you a dict?

I spent hours trying to find this one - where a single 1 line logging.warn() would have helped immensely.  If this warning / logging IS supposed to be happening, and I just don't see them - can you illuminate me what the appropriate debugging strategy is when you receive a ```<dict>``` instead of your expected class?

Thanks!

P

**Comment by svermeulen** [comment] 2020-12-16 09:11
I agree and was similarly confused for awhile when this happened.  I've taken the approach now of asserting that the result is never a dictionary

**Comment by davvid** [comment] 2020-12-21 01:22
Adding an `errors='ignore'` parameter to `decode(...)` seems like it would help this use case out.  It seems like it'd be relatively straightforward, too.  I can imagine supporting three values for the `errors` parameter: `{ignore,strict,warn}`.  `ignore` is what it does today, and can be the default.

Right now `_restore_object()` and `_restore_type()` both notice that `loadclass(...)` returns `None` and they throw theirs hands up and return the original `dict` when that happens.

When in the `errors='warn'` mode they can keep the same behavior and issue a warning.  When in the `errors='strict'` mode they could raise a `ValueError` exception instead.

I am suggesting `{ignore,warn,strict}` since the `ignore` and `strict` values are similar to `string.decode(..., errors='strict')` string API.

Not being able to load a class probably catches most of the use cases where this comes up, so the initial implementation could focus on that aspect, but it'd also leave the door open to expand it to other code paths as they come up.


What do you think?

**Comment by schperplata** [comment] 2021-02-19 10:53
Duplicate of #190

**Closed** 2022-05-05 17:01 UTC
