### ISSUE TITLE
encode() fails with "TypeError: string indices must be integers, not str"

### ISSUE THREAD

**Issue by edpark** [jsonpickle/jsonpickle#164] opened 2017-02-13 22:22 UTC
Trying to call encode on an object of mine fails with a TypeError on line 386 in pickler.py:

```
File "jsonpickle/pickler.py", line 386, in _flatten_obj_instance
    data[tags.REDUCE][3] = data[tags.REDUCE][3][tags.ITERATOR]
```

The value of data in this case is:
```
{'py/reduce': ["<type 'frozenset'>", '([],)', 'None', 'None', 'None']}
```

So it makes sense that I'm getting a TypeError but how is the value 'None' in the first place?

If I change my code from:
```
jsonpickle.encode(dto, unpicklable=False, max_depth=8)
```
to
```
jsonpickle.encode(dto, unpicklable=True, max_depth=8)
```
then it works.

Anyone know why this  would be happening?

**Comment by davvid** [comment] 2017-04-29 20:28
It's very hard to know what's going on without more context.

The best way to demonstrate the problem is to extend one of the test suite files (e.g. `tests/jsonpickle_test.py` or `tests/object_test.py`) and get the test suite running.

Add a minimal reproduction of the type of object you're pickling to reproduce your use can and then we'll have a permanent record of the use case in our test suite, which means it'll never get broken.

There might also be hints there about what's going on, depending on your use case.

**Comment by marcintustin** [comment] 2017-04-29 20:33
This has likely been fixed in the current master as a recent PR addressed a number of issues around built ins that reduce in this way. Please draw up a test case as @davvid suggests. If you can test against the affected version and master that would be great. 

If you can write the test but need help running it, let us know here.

**Comment by edpark** [comment] 2017-05-05 00:11
Hi @davvid and @marcintustin, while I'm having a bit of trouble coming up with a test case, I can confirm that the issue is fixed using the current master. Do you know when the next release is planned?

**Comment by davvid** [comment] 2017-05-05 06:33
I'll plan to tag a new release before the end of the month to allow some time for it to cook in master.

**Comment by edpark** [comment] 2017-06-27 23:52
Hi @davvid, any plans on releasing 0.9.5?

**Comment by davvid** [comment] 2017-07-17 03:16
`v0.9.5` was just tagged.

**Closed by davvid** 2017-07-17 03:16 UTC
