### ISSUE TITLE
How to keep order when encode OrderedDict with unpicklable=False

### ISSUE THREAD

**Issue by y-mironov** [jsonpickle/jsonpickle#288] opened 2020-02-14 11:11 UTC
I try this:

```python
bottom = OrderedDict([('z', 1), ('a', 2)])
middle = OrderedDict([('c', bottom)])
top = OrderedDict([('b', middle)])
encoded = jsonpickle.encode(top, unpicklable=False)
print(encoded)
```

result is
`{"b": {"c": {"a": 2, "z": 1}}}`

how do i get this
`{"b": {"c": {"z": 1, "a": 2}}}`
instead
`{"b": {"c": {"a": 2, "z": 1}}}`
?
Is it possible?

**Comment by davvid** [comment] 2020-02-22 21:09
Duplicate of #193

**Closed by davvid** 2020-02-22 21:09 UTC
