### ISSUE TITLE
Decoding datetime with tzinfo raises TypeError

### ISSUE THREAD

**Issue by GaNiziolek** [jsonpickle/jsonpickle#447] opened 2023-06-08 15:39 UTC
#### jsonpickle Version: 1.2

jsonpickle.decode function is raising `TypeError: 'NoneType' object is not callable` when pass some pickled object containing an datetime object with tzinfo.

datetime object without tzinfo works fine.

``` py
Python 3.10.12 (main, Jun  7 2023, 19:08:47) [GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from datetime import datetime
>>> from zoneinfo import ZoneInfo
>>> import jsonpickle
>>> 
>>> SaoPaulo = ZoneInfo('America/Sao_Paulo')
>>> 
>>> USEastern = ZoneInfo('US/Eastern')
>>> 
>>> now = datetime.now()
>>> now
datetime.datetime(2023, 6, 8, 15, 27, 1, 305282)
>>> 
>>> now_sp = now.replace(tzinfo=SaoPaulo)
>>> now_us = now.replace(tzinfo=USEastern)
>>> 
>>> pickled_now_sp = jsonpickle.encode(now_sp)
>>> pickled_now_us = jsonpickle.encode(now_us)
>>> pickled_now = jsonpickle.encode(now)
>>> 
>>> unpickled_now = jsonpickle.decode(pickled_now) # This works fine
>>> unpickled_now
datetime.datetime(2023, 6, 8, 15, 27, 1, 305282)
>>>
>>> unpickled_now_sp = jsonpickle.decode(pickled_now_sp) # This raise an error
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/python/3.10.12/lib/python3.10/site-packages/jsonpickle/unpickler.py", line 41, in decode
    return context.restore(data, reset=reset, classes=classes)
  File "/usr/local/python/3.10.12/lib/python3.10/site-packages/jsonpickle/unpickler.py", line 150, in restore
    value = self._restore(obj)
  File "/usr/local/python/3.10.12/lib/python3.10/site-packages/jsonpickle/unpickler.py", line 207, in _restore
    return restore(obj)
  File "/usr/local/python/3.10.12/lib/python3.10/site-packages/jsonpickle/unpickler.py", line 315, in _restore_object
    instance = handler(self).restore(obj)
  File "/usr/local/python/3.10.12/lib/python3.10/site-packages/jsonpickle/handlers.py", line 170, in restore
    params = (value,) + tuple([restore(i, reset=False) for i in args[1:]])
  File "/usr/local/python/3.10.12/lib/python3.10/site-packages/jsonpickle/handlers.py", line 170, in <listcomp>
    params = (value,) + tuple([restore(i, reset=False) for i in args[1:]])
  File "/usr/local/python/3.10.12/lib/python3.10/site-packages/jsonpickle/unpickler.py", line 150, in restore
    value = self._restore(obj)
  File "/usr/local/python/3.10.12/lib/python3.10/site-packages/jsonpickle/unpickler.py", line 207, in _restore
    return restore(obj)
  File "/usr/local/python/3.10.12/lib/python3.10/site-packages/jsonpickle/unpickler.py", line 242, in _restore_reduce
    stage1 = f(*args)
TypeError: 'NoneType' object is not callable
>>>
>>>
>>> unpickled_now_us = jsonpickle.decode(pickled_now_us) # diferent tz also raises the same error
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/python/3.10.12/lib/python3.10/site-packages/jsonpickle/unpickler.py", line 41, in decode
    return context.restore(data, reset=reset, classes=classes)
  File "/usr/local/python/3.10.12/lib/python3.10/site-packages/jsonpickle/unpickler.py", line 150, in restore
    value = self._restore(obj)
  File "/usr/local/python/3.10.12/lib/python3.10/site-packages/jsonpickle/unpickler.py", line 207, in _restore
    return restore(obj)
  File "/usr/local/python/3.10.12/lib/python3.10/site-packages/jsonpickle/unpickler.py", line 315, in _restore_object
    instance = handler(self).restore(obj)
  File "/usr/local/python/3.10.12/lib/python3.10/site-packages/jsonpickle/handlers.py", line 170, in restore
    params = (value,) + tuple([restore(i, reset=False) for i in args[1:]])
  File "/usr/local/python/3.10.12/lib/python3.10/site-packages/jsonpickle/handlers.py", line 170, in <listcomp>
    params = (value,) + tuple([restore(i, reset=False) for i in args[1:]])
  File "/usr/local/python/3.10.12/lib/python3.10/site-packages/jsonpickle/unpickler.py", line 150, in restore
    value = self._restore(obj)
  File "/usr/local/python/3.10.12/lib/python3.10/site-packages/jsonpickle/unpickler.py", line 207, in _restore
    return restore(obj)
  File "/usr/local/python/3.10.12/lib/python3.10/site-packages/jsonpickle/unpickler.py", line 242, in _restore_reduce
    stage1 = f(*args)
TypeError: 'NoneType' object is not callable
```

**Comment by GaNiziolek** [comment] 2023-06-12 20:54
I've tested with Python 3.11 and jsonpickle 3.0.1 and the error also occours, but the traceback is different

``` py
Python 3.11.3 (main, Apr  5 2023, 15:52:25) [GCC 12.2.1 20230201] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from datetime import datetime
>>> from zoneinfo import ZoneInfo
>>> import jsonpickle
>>> 
>>> SaoPaulo = ZoneInfo('America/Sao_Paulo')
>>> 
>>> now = datetime.now()
>>> 
>>> now
datetime.datetime(2023, 6, 12, 17, 53, 9, 845131)
>>> 
>>> now_sp = now.replace(tzinfo=SaoPaulo)
>>> now_sp
datetime.datetime(2023, 6, 12, 17, 53, 9, 845131, tzinfo=zoneinfo.ZoneInfo(key='America/Sao_Paulo'))
>>> 
>>> pickled_now = jsonpickle.encode(now)
>>> pickled_now
'{"py/object": "datetime.datetime", "__reduce__": [{"py/type": "datetime.datetime"}, ["B+cGDBE1CQzlSw=="]]}'
>>> 
>>> pickled_now_sp = jsonpickle.encode(now_sp)
>>> pickled_now_sp
'{"py/object": "datetime.datetime", "__reduce__": [{"py/type": "datetime.datetime"}, ["B+cGDBE1CQzlSw==", {"py/reduce": [{"py/function": "builtins.ZoneInfo._unpickle"}, {"py/tuple": ["America/Sao_Paulo", 1]}]}]]}'
>>> 
>>> jsonpickle.decode(pickled_now)
datetime.datetime(2023, 6, 12, 17, 53, 9, 845131)
>>> 
>>> jsonpickle.decode(pickled_now_sp)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/test_jsonpickle/venv/lib/python3.11/site-packages/jsonpickle/unpickler.py", line 88, in decode
    return context.restore(data, reset=reset, classes=classes)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/test_jsonpickle/venv/lib/python3.11/site-packages/jsonpickle/unpickler.py", line 362, in restore
    value = self._restore(obj)
            ^^^^^^^^^^^^^^^^^^
  File "/tmp/test_jsonpickle/venv/lib/python3.11/site-packages/jsonpickle/unpickler.py", line 344, in _restore
    return restore(obj)
           ^^^^^^^^^^^^
  File "/tmp/test_jsonpickle/venv/lib/python3.11/site-packages/jsonpickle/unpickler.py", line 769, in _restore_object
    instance = handler(self).restore(obj)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/test_jsonpickle/venv/lib/python3.11/site-packages/jsonpickle/handlers.py", line 195, in restore
    params = (value,) + tuple([restore(i, reset=False) for i in args[1:]])
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/test_jsonpickle/venv/lib/python3.11/site-packages/jsonpickle/handlers.py", line 195, in <listcomp>
    params = (value,) + tuple([restore(i, reset=False) for i in args[1:]])
                               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/test_jsonpickle/venv/lib/python3.11/site-packages/jsonpickle/unpickler.py", line 362, in restore
    value = self._restore(obj)
            ^^^^^^^^^^^^^^^^^^
  File "/tmp/test_jsonpickle/venv/lib/python3.11/site-packages/jsonpickle/unpickler.py", line 344, in _restore
    return restore(obj)
           ^^^^^^^^^^^^
  File "/tmp/test_jsonpickle/venv/lib/python3.11/site-packages/jsonpickle/unpickler.py", line 472, in _restore_reduce
    stage1 = f(*args)
             ^^^^^^^^
TypeError: 'module' object is not callable

```

**Comment by Theelx** [comment] 2023-06-14 00:17
Thanks for reporting this! I'll try to take a look in a few days when my work lightens up, but I think this'll be an easy fix.

**Comment by Theelx** [comment] 2023-06-15 17:46
Currently trying to figure this out, it seems the issue is that when the unpickler tries to restore ``builtins.ZoneInfo._unpickle``, it's restoring it into the builtins module, but not the function itself. I'm not currently sure how to fix it, but I'll keep trying!

**Comment by similegian** [comment] 2023-11-04 07:13
I have the same issue with python 3.12 and  jsonpickle Version: 3.0.2

The issue seems to be on the encoding side, the value {"py/reduce": [{"py/function": "builtins.ZoneInfo._unpickle"} (which used to be {"py/reduce": [{"py/function": "None.ZoneInfo._unpickle"} in previous versions) triggers the NoneType error when decoding.

We seem to have an issue resolving the module for the ZoneInfo class (util.importable_name(cls)) . It should be "zoneinfo" but comes back as None so it gets resolved as None or builtin. When decoding the class cannot be imported.

If I change the "py/function" value to "zoneinfo.ZoneInfo._unpickle" decoding works fine.

I am fairly new to Python and the logic in this library is not that easy to follow for a beginner like me, so not quite sure how to properly fix this ;)

**Comment by similegian** [comment] 2023-11-04 07:22
can use a simpler code, just with the zoneinfo class:

```
import jsonpickle
from zoneinfo import ZoneInfo

tz = ZoneInfo("America/New_York")
encoded_tz = jsonpickle.encode(tz)
print(encoded_tz)

# this fails with TypeError
decoded_tz = jsonpickle.decode(encoded_tz)
print(decoded_tz)

encoded_tz = encoded_tz.replace(
    "builtins.ZoneInfo._unpickle", "zoneinfo.ZoneInfo._unpickle"
)
print(encoded_tz)

# this works
decoded_tz = jsonpickle.decode(encoded_tz)
print(decoded_tz)

```

**Comment by similegian** [comment] 2023-11-04 07:44
The importable_name(cls) function in the util module attempts to resolve the module from cls.__self__.__class__.__module__

Stepping through the code with the debugger, for a ZoneInfo class, cls.__self__.__class__ is <class 'type'>

cls.__self__.__module__ is "zoneinfo" which is what we need.

Again, beginner Python dev here but maybe looking at  cls.__self__.__module__ first then cls.__self__.__class__.__module__ might fix this. Something like:

```
    module = translate_module_name(cls.__module__)
    if not module:
        if hasattr(cls, '__self__'):
            # >>> try cls.__self__.__module__ first
            module = cls.__self__.__module__
            if not module:
            # <<<
                module = cls.__self__.__class__.__module__

```

Took that for a test in my env and worked. Not sure what it breaks ;)

**Closed** 2023-11-12 22:18 UTC

**Comment by andmart** [comment] 2024-07-16 10:43
I am facing a similar problem, this time with solders. When jsonpickle tries to restore the object, the function field is prefixed with builtins: builtins.Pubkey.from_bytes

**jsonpickle**: 3.2.2
**python**: 3.11.4

**Example**

```
from solders.pubkey import Pubkey
import jsonpickle

p = Pubkey.new_unique()
print(str(p))
serial = jsonpickle.encode(p)
print(serial)
obj = jsonpickle.decode(serial)
print(str(obj)) 
```

The output in 7th line is :

`{"py/reduce": [{"py/function": "builtins.Pubkey.from_bytes"}, 
{"py/tuple": [{"py/b64": "AAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA="}]}]}`


The code produces the following error:

```
Traceback (most recent call last):
  File "/home/andmart/main.py", line 8, in <module>
    obj = jsonpickle.decode(serial)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andmart/.local/lib/python3.11/site-packages/jsonpickle/unpickler.py", line 98, in decode
    return context.restore(data, reset=reset, classes=classes)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andmart/.local/lib/python3.11/site-packages/jsonpickle/unpickler.py", line 383, in restore
    value = self._restore(obj)
            ^^^^^^^^^^^^^^^^^^
  File "/home/andmart/.local/lib/python3.11/site-packages/jsonpickle/unpickler.py", line 365, in _restore
    return restore(obj)
           ^^^^^^^^^^^^
  File "/home/andmart/.local/lib/python3.11/site-packages/jsonpickle/unpickler.py", line 498, in _restore_reduce
    stage1 = f(*args)
             ^^^^^^^^
TypeError: 'NoneType' object is not callable

```

**Comment by Theelx** [comment] 2024-07-18 14:46
Thanks for finding the issue and identifying a fix! I'll look into making a PR to merge a beautified version of this fix into the main branch. I've been very busy over the past few days, so I haven't had a chance to reply earlier, sorry!
