### ISSUE TITLE
shuffled values when deserialising :(

### ISSUE THREAD

**Issue by e3rd** [jsonpickle/jsonpickle#280] opened 2019-11-06 15:52 UTC
Hi guys,
thanks for this awesome tool.  

Version: Python 3.7.3, jsonpickle 1.2

I have found a serious bug that shuffles keys and values. It took me about 12 hours to spot the error and make a simple and reproducible demonstration. Run the code below and see the output.

Object pickled with `jsonpickle` genererated this output:
```python3
import jsonpickle

class Foo:  # formerly pickled object
    def __setstate__(self, state):
        self.__dict__ = state


class Bar:  # internal object used in Foo
    def __setstate__(self, state):
        self.state = state

    def __str__(self):
        return str(self.state)

# s is a json dump generated by jsonpickle
s = r"""{
  "py/object": "__main__.Foo",
  "py/state": {
    "ref_dict": {
      "json://{\"py/object\": \"__main__.Bar\", \"py/state\": 10}": {
        "py/tuple": []
      },
      "json://{\"py/object\": \"__main__.Bar\", \"py/state\": \"wrong ID 2\"}": {
        "py/tuple": []
      }
    },
    "my_dict": {
      "pointer-to-1": {"py/id": 1},
      "pointer-to-2": {"py/id": 2}
    }
  }
}"""


print(jsonpickle.decode(s, keys=True).my_dict["pointer-to-1"]) 
# should have printed "10"
# prints out "wrong ID 2" instead
```

It seems to me there is an internal sorting feature broken somewhere under the hood when referencing a `py/id` defined in a dict key.
We have seen that from `int(10)`, `"wrong ID 2"`, the latter was identified as `py/id 1`. Let's see a table of values, we mark as bold the one identified as `py/id 1` (whether it should be `py/id 1 or 2`) instead.

py/id 1 | py/id 2
------------ | -------------
int(10) | **wrong ID 2**
int(10) | **a**
**10** | a
z | **a**
**a** | z
**110** | 111
110 | **109**
**110** | 99
**int(110)** | int(111)
int(110) | **int(109)**
**int(110)** | int(99)

**Comment by davvid** [comment] 2019-11-07 08:13
Can you show me the complete code that generated that output?

**Comment by e3rd** [comment] 2019-11-07 10:00
I'll do my best to help but could you please specify? My code example was thoroughly tested to show the output.

**Comment by davvid** [comment] 2019-11-08 03:50
The code that generated that block of json.

**Comment by e3rd** [comment] 2019-11-08 13:14
By 'that block of json' you mean this table?
![image](https://user-images.githubusercontent.com/6942231/68479143-eb25d680-0231-11ea-98d0-92fc039d84d3.png)


That has not been generated at once. I've substitued red circles by the values py/id 1 and py/id 2, rerun the code snippet and made bold the one that was chosen.

![image](https://user-images.githubusercontent.com/6942231/68479101-cdf10800-0231-11ea-99d9-cd136d5510e5.png)

**Comment by e3rd** [comment] 2019-11-08 13:23
Aah, you mean the source block in the variable `s`, sorry! That one was several kilobytes long output of a program that asked whois, received `netaddr.IPRange` objects and generated this. The complete code of the program is too long for investigating. Since the encoding was alright I thought I render a good service by simplifying the jsonpickled object manually more and more while preserving the exactly same wrong output. Finally I made the variable `s`.

But if you say the problem is in the encoder rather than in the decoder, I'll try to find few hours next week the generate an object that is jsonpickled to `s`.

**Comment by davvid** [comment] 2019-11-09 21:49
Thank you, sorry for the misunderstanding.  It looks like the sorting for non-string keys is an issue, as this issue demonstrates.

**Comment by e3rd** [comment] 2019-11-11 17:28
I fear it seems the string keys are sorted badly as well. If I put 'a' and 'z', the first is always chosen.
![image](https://user-images.githubusercontent.com/6942231/68607524-166a2900-04b1-11ea-9346-8edd21e3b420.png)

**Comment by davvid** [comment] 2020-02-22 21:33
Duplicate of #288 
Already fixed.

**Closed by davvid** 2020-02-22 21:33 UTC

**Comment by e3rd** [comment] 2020-02-23 18:33
amazing!
